/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 1.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A ranked test or validation-context file for a scoped impact target.
 * @export
 * @interface ImpactValidationFile
 */
export interface ImpactValidationFile {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof ImpactValidationFile
     */
    file: string;
    /**
     * Ranking score for this validation file. Higher scores should be inspected first.
     * @type {number}
     * @memberof ImpactValidationFile
     */
    score: number;
    /**
     * Confidence tier for this validation file.
     * @type {string}
     * @memberof ImpactValidationFile
     */
    confidence: ImpactValidationFileConfidenceEnum;
    /**
     * Evidence used to rank the validation file.
     * @type {Array<string>}
     * @memberof ImpactValidationFile
     */
    reasons: Array<string>;
}


/**
 * @export
 */
export const ImpactValidationFileConfidenceEnum = {
    High: 'high',
    Medium: 'medium',
    Low: 'low'
} as const;
export type ImpactValidationFileConfidenceEnum = typeof ImpactValidationFileConfidenceEnum[keyof typeof ImpactValidationFileConfidenceEnum];


/**
 * Check if a given object implements the ImpactValidationFile interface.
 */
export function instanceOfImpactValidationFile(value: object): value is ImpactValidationFile {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('reasons' in value) || value['reasons'] === undefined) return false;
    return true;
}

export function ImpactValidationFileFromJSON(json: any): ImpactValidationFile {
    return ImpactValidationFileFromJSONTyped(json, false);
}

export function ImpactValidationFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactValidationFile {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'score': json['score'],
        'confidence': json['confidence'],
        'reasons': json['reasons'],
    };
}

export function ImpactValidationFileToJSON(value?: ImpactValidationFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'score': value['score'],
        'confidence': value['confidence'],
        'reasons': value['reasons'],
    };
}

